# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs: 
- deployment: VMRunCommadn
  displayName: RunCommand
  # environment:
  #   name: dev
  #   resourceType: VirtualMachine
  strategy:
      rolling:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: 'az version'
